[tool.poetry]
name = "ynot"
version = "0.6.2"
description = "A simple YT downloader GUI"
authors = ["Your Name"]

[tool.poetry.dependencies]
python = "^3.8"
yt-dlp = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
